name: BUILD KERNEL NEXT
on:
  workflow_dispatch:

jobs:
  build:
    uses: xiaoleGun/KernelSU_Action/.github/workflows/build.yml@main
    with:
      kernel-version: '6.6'
      ksu-version: 'next'
      additional-kconfig: |
        CONFIG_LOCALVERSION="-Samsung-S24U"
        CONFIG_KSU_SUSFS=y
        CONFIG_SUSFS_SPOOF_PROTO=y
